import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const messages = {
  ko: { search:'검색', login:'로그인', write:'글쓰기', writing:'작성 중', voteDay:'1Day 투표 참여', awards:'베스트 팝 아티스트', today:'오늘', weeks:'주간', month:'월간', views:'조회', empty:'검색 결과가 없습니다. 다른 키워드로 찾아보세요.', comments:'댓글', latest:'최신순 · 공감순', commentHint:'이 글에 대한 이야기를 남겨주세요.', charsLeft:'자 남음', submitComment:'댓글 등록', like:'공감', reply:'답글', authTitle:'팬들의 열기 속으로', signupTitle:'FAN HEAT 시작하기', authDesc:'좋아하는 아티스트와 더 뜨겁게 연결하세요.', signupDesc:'이메일 또는 간편 계정으로 가입할 수 있어요.', email:'이메일', password:'비밀번호', passwordHint:'6자 이상 입력', emailLogin:'이메일로 로그인', emailSignup:'이메일로 회원가입', processing:'처리 중…', or:'또는', google:'Google로 계속하기', kakao:'카카오로 계속하기', noAccount:'아직 계정이 없나요?', haveAccount:'이미 계정이 있나요?', signup:'회원가입', terms:'계속하면 FAN HEAT의 이용약관 및 개인정보 처리방침에 동의하게 됩니다.', newPost:'새 글 작성', close:'닫기', title:'제목', summary:'한줄 내용', upload:'업로드', addImage:'이미지 추가', content:'내용', tags:'태그', reference:'참조링크', addMusic:'음악 추가', musicSearch:'음원검색', revenue:'수익분배', publish:'작성하기', defaultSummary:'K-POP 팬들이 함께 나누는 새로운 이야기입니다.', language:'언어 선택' },
  en: { search:'Search', login:'Log in', write:'Write', writing:'Editing', voteDay:'Join 1Day Vote', awards:'K-POP Best Awards', today:'Today', weeks:'Weekly', month:'Monthly', views:'Views', empty:'No results found. Try another keyword.', comments:'Comments', latest:'Newest · Most liked', commentHint:'Share your thoughts about this post.', charsLeft:' characters left', submitComment:'Post comment', like:'Like', reply:'Reply', authTitle:'Feel the heat of fandom', signupTitle:'Join FAN HEAT', authDesc:'Connect more closely with the artists you love.', signupDesc:'Sign up with email or a social account.', email:'Email', password:'Password', passwordHint:'At least 6 characters', emailLogin:'Log in with email', emailSignup:'Sign up with email', processing:'Working…', or:'or', google:'Continue with Google', kakao:'Continue with Kakao', noAccount:'New to FAN HEAT?', haveAccount:'Already have an account?', signup:'Sign up', terms:'By continuing, you agree to FAN HEAT’s Terms and Privacy Policy.', newPost:'Create post', close:'Close', title:'Title', summary:'Short summary', upload:'Upload', addImage:'Add images', content:'Content', tags:'Tags', reference:'Reference link', addMusic:'Add music', musicSearch:'Find music', revenue:'Revenue share', publish:'Publish', defaultSummary:'A new K-POP story shared by fans.', language:'Select language' },
  ja: { search:'検索', login:'ログイン', write:'投稿する', writing:'編集中', voteDay:'1Day投票に参加', awards:'K-POP ベストアワード', today:'今日', weeks:'週間', month:'月間', views:'閲覧', empty:'検索結果がありません。別のキーワードをお試しください。', comments:'コメント', latest:'新着順・共感順', commentHint:'この投稿へのコメントを入力してください。', charsLeft:'文字残り', submitComment:'コメントする', like:'共感', reply:'返信', authTitle:'ファンの熱気の中へ', signupTitle:'FAN HEATを始める', authDesc:'好きなアーティストともっと熱くつながろう。', signupDesc:'メールまたはソーシャルアカウントで登録できます。', email:'メール', password:'パスワード', passwordHint:'6文字以上', emailLogin:'メールでログイン', emailSignup:'メールで新規登録', processing:'処理中…', or:'または', google:'Googleで続ける', kakao:'カカオで続ける', noAccount:'アカウントをお持ちでないですか？', haveAccount:'すでにアカウントをお持ちですか？', signup:'新規登録', terms:'続行するとFAN HEATの利用規約とプライバシーポリシーに同意したものとみなされます。', newPost:'新しい投稿', close:'閉じる', title:'タイトル', summary:'一行説明', upload:'アップロード', addImage:'画像を追加', content:'本文', tags:'タグ', reference:'参考リンク', addMusic:'音楽を追加', musicSearch:'音楽検索', revenue:'収益分配', publish:'投稿する', defaultSummary:'K-POPファンが共有する新しいストーリーです。', language:'言語を選択' },
}

const titleMap = {
  en: { '트와이스 사나':'TWICE Sana', '레드벨벳 슬기 웬디 - 배틀트립':'Red Velvet Seulgi & Wendy – Battle Trip', '프로듀스48 연습생 - 김도아':'Produce 48 Trainee – Kim Doah', '7월 27일 치바 에리이 트위터 사진':'Chiba Erii Twitter Photos – July 27', '하니의 에나멜 의상 뒷태':"Hani's Enamel Stage Outfit", '모모랜드 데이지':'MOMOLAND Daisy', '설리 비키니 + 딸기':'Sulli, Bikini & Strawberry', '여행':'Travel', '키스 먼저 할까요':'Should We Kiss First?', '지나오다':'Passing By' },
  ja: { '트와이스 사나':'TWICE サナ', '레드벨벳 슬기 웬디 - 배틀트립':'Red Velvet スルギ＆ウェンディ－バトルトリップ', '프로듀스48 연습생 - 김도아':'PRODUCE 48 練習生－キム・ドア', '7월 27일 치바 에리이 트위터 사진':'千葉恵里 7月27日 Twitter写真', '하니의 에나멜 의상 뒷태':'ハニのエナメル衣装', '모모랜드 데이지':'MOMOLAND デイジー', '설리 비키니 + 딸기':'ソルリ、ビキニ＆いちご', '여행':'旅行', '키스 먼저 할까요':'先にキスからしましょうか', '지나오다':'通り過ぎる' },
}

const I18nContext = createContext(null)
export function I18nProvider({ children }) {
  const [locale, setLocaleState] = useState(() => localStorage.getItem('fanheat-locale') || 'ko')
  useEffect(() => { document.documentElement.lang = locale }, [locale])
  const setLocale = next => { localStorage.setItem('fanheat-locale', next); document.documentElement.lang = next; setLocaleState(next) }
  const value = useMemo(() => ({ locale, setLocale, t:key => messages[locale]?.[key] ?? messages.ko[key] ?? key, localizeTitle:value => titleMap[locale]?.[value] ?? value }), [locale])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}
export const useI18n = () => useContext(I18nContext)
