-- Store complete album and track details in Supabase and expose them through
-- the Data API. Prototype content is intentionally not seeded as production data.

alter table public.artist_albums
  add column if not exists description text,
  add column if not exists label text,
  add column if not exists genre text,
  add column if not exists external_url text;

create table if not exists public.artist_album_tracks (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.artist_albums(id) on delete cascade,
  track_number integer not null default 1 check (track_number between 1 and 999),
  title text not null check (char_length(title) between 1 and 300),
  duration_text text,
  lyrics_excerpt text,
  youtube_url text,
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (album_id, track_number)
);

create index if not exists artist_album_tracks_album_order_idx
  on public.artist_album_tracks(album_id, active desc, display_order, track_number);

alter table public.artist_album_tracks enable row level security;
grant select on public.artist_album_tracks to anon;
grant select, insert, update, delete on public.artist_album_tracks to authenticated;
grant usage, select on sequence public.artist_album_tracks_id_seq to authenticated;

drop policy if exists artist_album_tracks_visible_read on public.artist_album_tracks;
drop policy if exists artist_album_tracks_admin_insert on public.artist_album_tracks;
drop policy if exists artist_album_tracks_admin_update on public.artist_album_tracks;
drop policy if exists artist_album_tracks_admin_delete on public.artist_album_tracks;
create policy artist_album_tracks_visible_read on public.artist_album_tracks
  for select to public using (
    active and exists (
      select 1 from public.artist_albums album
      where album.id = album_id and album.active
    )
    or (select public.is_admin())
  );
create policy artist_album_tracks_admin_insert on public.artist_album_tracks
  for insert to authenticated with check ((select public.is_admin()));
create policy artist_album_tracks_admin_update on public.artist_album_tracks
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy artist_album_tracks_admin_delete on public.artist_album_tracks
  for delete to authenticated using ((select public.is_admin()));

drop trigger if exists audit_artist_album_tracks on public.artist_album_tracks;
create trigger audit_artist_album_tracks
  after insert or update or delete on public.artist_album_tracks
  for each row execute function public.log_admin_change();
