-- Expand the React/Supabase back office so artists, posts, and nested comments
-- can be managed without the removed Spring service.

alter table public.artists
  add column if not exists real_name text,
  add column if not exists role_description text,
  add column if not exists debut_text text,
  add column if not exists agency text,
  add column if not exists fandom_name text,
  add column if not exists hero_image_url text,
  add column if not exists bio_paragraphs text[] not null default '{}',
  add column if not exists history_items jsonb not null default '[]'::jsonb,
  add column if not exists award_items jsonb not null default '[]'::jsonb,
  add column if not exists follower_count bigint not null default 0 check (follower_count >= 0),
  add column if not exists visitor_today bigint not null default 0 check (visitor_today >= 0),
  add column if not exists visitor_total bigint not null default 0 check (visitor_total >= 0),
  add column if not exists facebook_url text,
  add column if not exists x_url text,
  add column if not exists instagram_url text,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.artist_albums (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  lead_track text not null default '',
  release_date date,
  album_type text not null default '앨범',
  track_count integer not null default 1 check (track_count between 0 and 200),
  cover_url text,
  youtube_url text,
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.artist_gallery_items (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  image_url text not null,
  captured_on date,
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.artist_fans (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  profile_id uuid references public.profiles(id) on delete set null,
  display_name text not null,
  handle text not null,
  avatar_url text,
  heat_percent integer not null default 0 check (heat_percent between 0 and 100),
  featured_rank integer check (featured_rank between 1 and 999),
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Only structural deletion metadata is public. The deleted comment body remains
-- protected by the comments RLS policy and is never copied into this table.
create table if not exists public.comment_tombstones (
  comment_id uuid primary key references public.comments(id) on delete cascade,
  post_id uuid not null references public.posts(id) on delete cascade,
  parent_id uuid,
  deleted_at timestamptz not null default now()
);

create index if not exists artist_albums_artist_order_idx
  on public.artist_albums(artist_id, active desc, display_order, release_date desc);
create index if not exists artist_gallery_artist_order_idx
  on public.artist_gallery_items(artist_id, active desc, display_order, captured_on desc);
create index if not exists artist_fans_artist_order_idx
  on public.artist_fans(artist_id, active desc, display_order, featured_rank);
create index if not exists comment_tombstones_post_idx
  on public.comment_tombstones(post_id, deleted_at);
create index if not exists comment_tombstones_parent_idx
  on public.comment_tombstones(parent_id) where parent_id is not null;

alter table public.artist_albums enable row level security;
alter table public.artist_gallery_items enable row level security;
alter table public.artist_fans enable row level security;
alter table public.comment_tombstones enable row level security;

grant select on public.artist_albums, public.artist_gallery_items, public.artist_fans to anon;
grant select, insert, update, delete on public.artist_albums, public.artist_gallery_items, public.artist_fans to authenticated;
grant select on public.comment_tombstones to anon;
grant select, insert, update, delete on public.comment_tombstones to authenticated;
grant usage, select on sequence public.artist_albums_id_seq, public.artist_gallery_items_id_seq, public.artist_fans_id_seq to authenticated;

drop policy if exists artist_albums_visible_read on public.artist_albums;
drop policy if exists artist_albums_admin_insert on public.artist_albums;
drop policy if exists artist_albums_admin_update on public.artist_albums;
drop policy if exists artist_albums_admin_delete on public.artist_albums;
create policy artist_albums_visible_read on public.artist_albums
  for select to public using (active or (select public.is_admin()));
create policy artist_albums_admin_insert on public.artist_albums
  for insert to authenticated with check ((select public.is_admin()));
create policy artist_albums_admin_update on public.artist_albums
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy artist_albums_admin_delete on public.artist_albums
  for delete to authenticated using ((select public.is_admin()));

drop policy if exists artist_gallery_visible_read on public.artist_gallery_items;
drop policy if exists artist_gallery_admin_insert on public.artist_gallery_items;
drop policy if exists artist_gallery_admin_update on public.artist_gallery_items;
drop policy if exists artist_gallery_admin_delete on public.artist_gallery_items;
create policy artist_gallery_visible_read on public.artist_gallery_items
  for select to public using (active or (select public.is_admin()));
create policy artist_gallery_admin_insert on public.artist_gallery_items
  for insert to authenticated with check ((select public.is_admin()));
create policy artist_gallery_admin_update on public.artist_gallery_items
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy artist_gallery_admin_delete on public.artist_gallery_items
  for delete to authenticated using ((select public.is_admin()));

drop policy if exists artist_fans_visible_read on public.artist_fans;
drop policy if exists artist_fans_admin_insert on public.artist_fans;
drop policy if exists artist_fans_admin_update on public.artist_fans;
drop policy if exists artist_fans_admin_delete on public.artist_fans;
create policy artist_fans_visible_read on public.artist_fans
  for select to public using (active or (select public.is_admin()));
create policy artist_fans_admin_insert on public.artist_fans
  for insert to authenticated with check ((select public.is_admin()));
create policy artist_fans_admin_update on public.artist_fans
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy artist_fans_admin_delete on public.artist_fans
  for delete to authenticated using ((select public.is_admin()));

drop policy if exists comment_tombstones_public_read on public.comment_tombstones;
drop policy if exists comment_tombstones_owner_or_admin_insert on public.comment_tombstones;
drop policy if exists comment_tombstones_admin_update on public.comment_tombstones;
drop policy if exists comment_tombstones_admin_delete on public.comment_tombstones;
create policy comment_tombstones_public_read on public.comment_tombstones
  for select to public using (true);
create policy comment_tombstones_owner_or_admin_insert on public.comment_tombstones
  for insert to authenticated with check (
    (select public.is_admin()) or exists (
      select 1 from public.comments c
      where c.id = comment_id and c.author_id = (select auth.uid())
    )
  );
create policy comment_tombstones_admin_update on public.comment_tombstones
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy comment_tombstones_admin_delete on public.comment_tombstones
  for delete to authenticated using ((select public.is_admin()));

-- Keep post media editable by the post owner and by a super administrator.
drop policy if exists post_images_owner_insert on public.post_images;
drop policy if exists post_images_owner_update on public.post_images;
drop policy if exists post_images_owner_delete on public.post_images;
drop policy if exists post_images_owner_or_admin_insert on public.post_images;
drop policy if exists post_images_owner_or_admin_update on public.post_images;
drop policy if exists post_images_owner_or_admin_delete on public.post_images;
create policy post_images_owner_or_admin_insert on public.post_images
  for insert to authenticated with check (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.author_id = (select auth.uid()) or (select public.is_admin()))
  ));
create policy post_images_owner_or_admin_update on public.post_images
  for update to authenticated using (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.author_id = (select auth.uid()) or (select public.is_admin()))
  )) with check (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.author_id = (select auth.uid()) or (select public.is_admin()))
  ));
create policy post_images_owner_or_admin_delete on public.post_images
  for delete to authenticated using (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.author_id = (select auth.uid()) or (select public.is_admin()))
  ));

drop trigger if exists audit_artist_albums on public.artist_albums;
create trigger audit_artist_albums after insert or update or delete on public.artist_albums
  for each row execute function public.log_admin_change();
drop trigger if exists audit_artist_gallery_items on public.artist_gallery_items;
create trigger audit_artist_gallery_items after insert or update or delete on public.artist_gallery_items
  for each row execute function public.log_admin_change();
drop trigger if exists audit_artist_fans on public.artist_fans;
create trigger audit_artist_fans after insert or update or delete on public.artist_fans
  for each row execute function public.log_admin_change();

insert into public.comment_tombstones(comment_id, post_id, parent_id, deleted_at)
select id, post_id, parent_id, deleted_at
from public.comments
where deleted_at is not null
on conflict (comment_id) do nothing;
