with enriched(slug, bio_paragraphs, history_items, award_items) as (
  values
  ('kwon-eun-bi-q56505060', array[
    '권은비는 IZ*ONE의 리더로 이름을 알린 뒤 2021년 미니 앨범 《OPEN》으로 솔로 활동을 시작한 가수입니다. 안정적인 보컬과 선명한 춤선, 무대를 장악하는 표현력을 함께 보여 줍니다.',
    '《Color》, 《Lethality》, 《The Flash》, 《SABOTAGE》 등으로 솔로 디스코그래피를 넓혔고, 특히 ‘Underwater’의 역주행과 여름 페스티벌 무대로 대중적인 존재감을 키웠습니다.'
  ], '[{"year":"2018","text":"Mnet 《프로듀스 48》 최종 7위로 IZ*ONE 데뷔조에 합류.","source_url":"https://en.wikipedia.org/wiki/Kwon_Eun-bi"},{"year":"2021","text":"IZ*ONE 활동을 마친 뒤 미니 1집 《OPEN》으로 솔로 데뷔.","source_url":"https://www.yna.co.kr/view/AKR20210824157600005"},{"year":"2022","text":"《Color》와 《Lethality》를 발표하며 솔로 음악 색을 확장.","source_url":"https://en.wikipedia.org/wiki/Kwon_Eun-bi"},{"year":"2023","text":"워터밤 무대 이후 ‘Underwater’가 역주행하며 여름 대표 솔로 가수로 주목.","source_url":"https://www.hankyung.com/article/202307039489H"},{"year":"2024","text":"싱글 《SABOTAGE》를 발표하고 국내외 활동을 이어감.","source_url":"https://weverse.io/kwoneunbi/notice/20325"}]'::jsonb,
  '[{"year":"2021","text":"Asia Artist Awards 이모티브상 수상.","source_url":"https://www.asiaartistawards.com/artist/detail/616/aaa/3"},{"year":"2023","text":"《더 쇼》 ‘The Flash’로 솔로 첫 음악방송 1위.","source_url":"https://en.wikipedia.org/wiki/Kwon_Eun-bi"},{"year":"2023","text":"Asia Artist Awards 베스트 뮤지션상 수상.","source_url":"https://www.asiaartistawards.com/news/detail/72944/all"},{"year":"2024","text":"MTN 방송광고 페스티벌 CF스타상 신인상 수상.","source_url":"https://mice.mtn.co.kr/notice/5902c0a5-5b8d-4143-add2-2d84ec33f0f8"}]'::jsonb),

  ('bts-q13580495', array[
    '방탄소년단은 RM, 진, 슈가, 제이홉, 지민, 뷔, 정국으로 구성된 7인조 그룹입니다. 2013년 데뷔 후 청춘의 고민과 성장, 자기 사랑을 연결한 앨범 서사와 직접 참여한 음악으로 세계적인 팬덤을 만들었습니다.',
    '한국 가수 최초의 빌보드 주요 차트 기록과 그래미 어워드 단독 무대, 스타디움 투어를 달성했으며 UN 연설과 LOVE MYSELF 캠페인으로 음악 밖에서도 영향력을 이어 왔습니다.'
  ], '[{"year":"2013","text":"싱글 앨범 《2 COOL 4 SKOOL》과 ‘No More Dream’으로 데뷔.","source_url":"https://ibighit.com/bts/kor/profile/"},{"year":"2017","text":"Billboard Music Awards에서 Top Social Artist를 수상하며 미국 활동의 전환점을 마련.","source_url":"https://ibighit.com/bts/kor/profile/"},{"year":"2020","text":"‘Dynamite’로 한국 가수 최초 Billboard Hot 100 1위 달성.","source_url":"https://ibighit.com/bts/kor/profile/"},{"year":"2022","text":"앤솔러지 앨범 《Proof》로 첫 장을 정리하고 멤버별 활동을 병행.","source_url":"https://bts.ibighit.com/eng/discography/"},{"year":"2026","text":"정규 5집 《ARIRANG》으로 그룹 디스코그래피를 재개.","source_url":"https://bts.ibighit.com/eng/discography/"}]'::jsonb,
  '[{"year":"2016","text":"Melon Music Awards 올해의 앨범상으로 첫 대상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_BTS"},{"year":"2017","text":"Billboard Music Awards Top Social Artist 수상.","source_url":"https://www.billboard.com/music/awards/bts-wins-top-social-artist-billboard-music-awards-2017-7801212/"},{"year":"2021","text":"American Music Awards Artist of the Year 수상.","source_url":"https://www.theamas.com/winners/2021-winners/"},{"year":"2022","text":"MAMA Awards 올해의 가수·Worldwide Icon of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_BTS"}]'::jsonb),

  ('blackpink-q25056945', array[
    'BLACKPINK는 지수, 제니, 로제, 리사로 구성된 YG Entertainment의 걸 그룹입니다. 힙합 기반의 강한 사운드와 멤버별 음색, 패션과 퍼포먼스를 결합한 팀 컬러로 세계적인 영향력을 구축했습니다.',
    '‘DDU-DU DDU-DU’, ‘Kill This Love’, ‘How You Like That’, ‘Pink Venom’ 등으로 글로벌 차트와 대형 공연 무대를 넓혔으며, 그룹과 솔로 활동을 함께 전개하고 있습니다.'
  ], '[{"year":"2016","text":"싱글 《SQUARE ONE》의 ‘WHISTLE’과 ‘BOOMBAYAH’로 데뷔.","source_url":"https://ygfamily.com/en/artists/blackpink/profile"},{"year":"2018","text":"‘DDU-DU DDU-DU’와 첫 미니 앨범 《SQUARE UP》으로 글로벌 인지도를 확대.","source_url":"https://ygfamily.com/en/artists/blackpink/discography"},{"year":"2020","text":"첫 정규 앨범 《THE ALBUM》을 발표하고 Billboard 200 2위 기록.","source_url":"https://en.wikipedia.org/wiki/Blackpink"},{"year":"2022","text":"정규 2집 《BORN PINK》과 월드 투어를 전개.","source_url":"https://ygfamily.com/en/artists/blackpink/profile"},{"year":"2026","text":"앨범 《DEADLINE》으로 그룹 활동을 이어감.","source_url":"https://ygfamily.com/en/artists/blackpink/discography"}]'::jsonb,
  '[{"year":"2020","text":"MAMA Awards Best Female Group 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Blackpink"},{"year":"2022","text":"MTV Video Music Awards Best Metaverse Performance 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Blackpink"},{"year":"2023","text":"Circle Chart Music Awards 올해의 여자 그룹 등 4개 부문 수상.","source_url":"https://ygfamily.com/en/artists/blackpink/profile"},{"year":"2026","text":"Golden Disc Awards Best Digital Song 수상.","source_url":"https://ygfamily.com/en/artists/blackpink/profile"}]'::jsonb),

  ('twice-q20645861', array[
    'TWICE는 JYP Entertainment의 9인조 걸 그룹으로, 밝고 친근한 에너지와 멤버별 개성이 살아 있는 퍼포먼스로 사랑받아 왔습니다. ‘OOH-AHH하게’부터 ‘CHEER UP’, ‘TT’, ‘FANCY’까지 세대별 대표곡을 쌓았습니다.',
    '한국과 일본을 오가는 탄탄한 디스코그래피에 영어 싱글과 대규모 투어를 더하며 활동 영역을 넓혔고, 유닛과 솔로 활동도 함께 선보이고 있습니다.'
  ], '[{"year":"2015","text":"오디션 《SIXTEEN》을 거쳐 미니 앨범 《THE STORY BEGINS》로 데뷔.","source_url":"https://twice.jype.com/"},{"year":"2016","text":"‘CHEER UP’과 ‘TT’가 연이어 히트하며 대표 걸 그룹으로 성장.","source_url":"https://en.wikipedia.org/wiki/Twice"},{"year":"2017","text":"일본 정식 데뷔 후 아레나·돔 공연으로 활동 범위를 확대.","source_url":"https://wmg.jp/twice"},{"year":"2021","text":"첫 영어 싱글 ‘The Feels’로 Billboard Hot 100 진입.","source_url":"https://en.wikipedia.org/wiki/Twice"},{"year":"2025","text":"정규 앨범 《THIS IS FOR》와 스페셜 앨범 《TEN: The Story Goes On》 발표.","source_url":"https://twice.jype.com/"}]'::jsonb,
  '[{"year":"2015","text":"MAMA Awards Best New Female Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Twice"},{"year":"2016","text":"‘CHEER UP’으로 MAMA Awards Song of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Twice"},{"year":"2017","text":"‘SIGNAL’로 MAMA Awards Song of the Year 2년 연속 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Twice"},{"year":"2020","text":"Golden Disc Awards 음반 본상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Twice"}]'::jsonb),

  ('stray-kids-q46134670', array[
    'Stray Kids는 방찬, 리노, 창빈, 현진, 한, 필릭스, 승민, 아이엔으로 활동하는 JYP Entertainment의 보이 그룹입니다. 3RACHA를 중심으로 멤버들이 작사·작곡·프로듀싱에 폭넓게 참여합니다.',
    '강렬한 힙합과 전자음, 솔직한 성장 서사를 결합한 음악으로 독자적인 색을 만들었으며 ‘God’s Menu’, ‘MANIAC’, ‘CASE 143’, ‘Chk Chk Boom’ 등을 통해 세계적인 투어 규모를 키웠습니다.'
  ], '[{"year":"2018","text":"미니 앨범 《I am NOT》과 ‘District 9’으로 정식 데뷔.","source_url":"https://straykids.jype.com/"},{"year":"2020","text":"《GO LIVE》의 ‘God’s Menu’로 팀의 대표적인 음악 색을 확립.","source_url":"https://straykids.jype.com/discography"},{"year":"2021","text":"《NOEASY》가 팀의 첫 밀리언셀러 앨범 기록.","source_url":"https://en.wikipedia.org/wiki/Stray_Kids"},{"year":"2022","text":"《ODDINARY》로 Billboard 200 첫 1위 달성.","source_url":"https://en.wikipedia.org/wiki/Stray_Kids"},{"year":"2024","text":"《ATE》와 월드 투어로 글로벌 활동을 확장.","source_url":"https://straykids.jype.com/discography"}]'::jsonb,
  '[{"year":"2018","text":"MAMA Awards Best New Male Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Stray_Kids"},{"year":"2021","text":"Mnet 《Kingdom: Legendary War》 최종 우승.","source_url":"https://en.wikipedia.org/wiki/Stray_Kids"},{"year":"2023","text":"MTV Video Music Awards Best K-Pop 수상.","source_url":"https://www.mtv.com/vma/vote/"},{"year":"2024","text":"Billboard Music Awards Top Global K-Pop Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Stray_Kids"}]'::jsonb),

  ('seventeen-q14524548', array[
    'SEVENTEEN은 13명의 멤버가 힙합·보컬·퍼포먼스 세 유닛으로 협업하는 그룹입니다. 멤버들이 음악 제작과 안무에 적극 참여하는 자체 제작 시스템과 정교한 군무, 밝은 에너지가 팀의 핵심입니다.',
    '《17 CARAT》으로 시작해 《An Ode》, 《Face the Sun》, 《FML》, 《HAPPY BURSTDAY》까지 성장 서사를 이어 왔으며 CARAT과 함께 대형 투어와 글로벌 활동을 전개하고 있습니다.'
  ], '[{"year":"2015","text":"미니 앨범 《17 CARAT》으로 데뷔.","source_url":"https://www.pledis.co.kr/en/artist/detail/seventeen/profile/"},{"year":"2016","text":"첫 정규 앨범 《LOVE & LETTER》와 ‘예쁘다’를 발표.","source_url":"https://en.wikipedia.org/wiki/Seventeen_(South_Korean_band)"},{"year":"2021","text":"멤버 13명 전원이 PLEDIS와 재계약.","source_url":"https://en.wikipedia.org/wiki/Seventeen_(South_Korean_band)"},{"year":"2023","text":"《FML》과 ‘손오공’으로 음반·공연 성과를 확대.","source_url":"https://www.seventeen-17.jp/posts/discography"},{"year":"2025","text":"데뷔 10주년에 정규 5집 《HAPPY BURSTDAY》 발표.","source_url":"https://www.seventeen-17.jp/"}]'::jsonb,
  '[{"year":"2016","text":"Golden Disc Awards 신인상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Seventeen"},{"year":"2023","text":"《FML》로 MAMA Awards Album of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/Seventeen_(South_Korean_band)"},{"year":"2024","text":"MAMA Awards Artist of the Year와 Album of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/Seventeen_(South_Korean_band)"},{"year":"2024","text":"Billboard Music Awards Top K-Pop Touring Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Seventeen"}]'::jsonb),

  ('aespa-q100877982', array[
    'aespa는 카리나, 지젤, 윈터, 닝닝으로 구성된 SM Entertainment의 걸 그룹입니다. 강한 전자음과 가상 세계관에서 출발해 메탈릭한 스타일, 탄탄한 보컬과 퍼포먼스를 결합해 왔습니다.',
    '‘Black Mamba’, ‘Next Level’, ‘Spicy’, ‘Drama’, ‘Supernova’ 등 서로 다른 질감의 히트곡을 만들었고 정규 앨범과 글로벌 투어, 일본 활동으로 음악 세계를 넓히고 있습니다.'
  ], '[{"year":"2020","text":"디지털 싱글 ‘Black Mamba’로 데뷔.","source_url":"https://en.wikipedia.org/wiki/Aespa"},{"year":"2021","text":"‘Next Level’과 미니 앨범 《Savage》로 대중성과 세계관을 확장.","source_url":"https://en.wikipedia.org/wiki/Aespa"},{"year":"2022","text":"Coachella 메인 스테이지에서 공연.","source_url":"https://en.wikipedia.org/wiki/Aespa"},{"year":"2024","text":"첫 정규 앨범 《Armageddon》과 ‘Supernova’를 발표.","source_url":"https://en.wikipedia.org/wiki/Aespa"},{"year":"2026","text":"일본 미니 앨범 《KISS N TELL》로 활동을 이어감.","source_url":"https://wmg.jp/aespa/discography"}]'::jsonb,
  '[{"year":"2021","text":"‘Next Level’로 Korean Music Awards Song of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Aespa"},{"year":"2021","text":"Melon Music Awards Record of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Aespa"},{"year":"2024","text":"‘Supernova’로 MAMA Awards Song of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Aespa"},{"year":"2024","text":"Melon Music Awards 올해의 앨범·올해의 노래·올해의 아티스트 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Aespa"}]'::jsonb),

  ('ive-q109375061', array[
    'IVE는 안유진, 가을, 레이, 장원영, 리즈, 이서로 구성된 Starship Entertainment의 걸 그룹입니다. 자기 확신을 중심으로 한 가사와 우아하면서도 힘 있는 퍼포먼스, 멤버별 음색이 팀의 특징입니다.',
    '‘ELEVEN’, ‘LOVE DIVE’, ‘After LIKE’, ‘I AM’이 연속으로 사랑받으며 빠르게 대표 걸 그룹으로 성장했고, 한국과 일본 앨범 및 월드 투어로 활동 영역을 확장했습니다.'
  ], '[{"year":"2021","text":"싱글 앨범 《ELEVEN》으로 데뷔.","source_url":"https://ive-official.jp/"},{"year":"2022","text":"‘LOVE DIVE’와 ‘After LIKE’가 연이어 히트하며 연말 대상을 수상.","source_url":"https://ssl.sme.co.jp/artist/IVE/profile/"},{"year":"2023","text":"첫 정규 앨범 《I’ve IVE》와 ‘I AM’을 발표.","source_url":"https://en.wikipedia.org/wiki/Ive_(group)"},{"year":"2024","text":"미니 앨범 《IVE SWITCH》와 첫 월드 투어를 전개.","source_url":"https://en.wikipedia.org/wiki/Ive_discography"},{"year":"2026","text":"일본 EP 《LUCID DREAM》으로 활동을 이어감.","source_url":"https://ive-official.jp/"}]'::jsonb,
  '[{"year":"2022","text":"MAMA Awards Best New Female Artist와 Song of the Year 수상.","source_url":"https://ssl.sme.co.jp/artist/IVE/profile/"},{"year":"2022","text":"Melon Music Awards Song of the Year와 신인상 수상.","source_url":"https://ssl.sme.co.jp/artist/IVE/profile/"},{"year":"2023","text":"Golden Disc Awards 디지털 음원 대상·본상·신인상 수상.","source_url":"https://ssl.sme.co.jp/artist/IVE/profile/"},{"year":"2023","text":"《I’ve IVE》로 Melon Music Awards Album of the Year 수상.","source_url":"https://ssl.sme.co.jp/artist/IVE/profile/"}]'::jsonb),

  ('le-sserafim-q111381707', array[
    'LE SSERAFIM은 사쿠라, 김채원, 허윤진, 카즈하, 홍은채로 구성된 SOURCE MUSIC의 5인조 걸 그룹입니다. 팀명은 I’M FEARLESS의 애너그램으로, 시선에 흔들리지 않고 앞으로 나아가겠다는 메시지를 담습니다.',
    '‘FEARLESS’, ‘ANTIFRAGILE’, ‘UNFORGIVEN’, ‘EASY’, ‘CRAZY’, ‘HOT’으로 자신감과 성장의 서사를 이어 왔으며 강인함과 우아함을 함께 보여 주는 퍼포먼스가 특징입니다.'
  ], '[{"year":"2022","text":"미니 앨범 《FEARLESS》로 데뷔하고 5인조 체제로 활동을 정비.","source_url":"https://le-sserafim.com/"},{"year":"2022","text":"《ANTIFRAGILE》로 팀의 음악적 정체성을 선명하게 확장.","source_url":"https://www.le-sserafim.jp/discography"},{"year":"2023","text":"첫 정규 앨범 《UNFORGIVEN》과 영어 싱글 ‘Perfect Night’ 발표.","source_url":"https://www.le-sserafim.jp/discography"},{"year":"2024","text":"《EASY》·《CRAZY》 발표와 Coachella 공연으로 글로벌 활동 확대.","source_url":"https://en.wikipedia.org/wiki/Le_Sserafim"},{"year":"2025","text":"미니 앨범 《HOT》을 발표하고 투어를 이어감.","source_url":"https://www.le-sserafim.jp/discography"}]'::jsonb,
  '[{"year":"2022","text":"MAMA Awards Favorite New Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Le_Sserafim"},{"year":"2023","text":"Asia Artist Awards Best Performance상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Le_Sserafim"},{"year":"2024","text":"MTV Europe Music Awards Best Push 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Le_Sserafim"},{"year":"2026","text":"Seoul Music Awards 본상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Le_Sserafim"}]'::jsonb),

  ('newjeans-q113189277', array[
    'NewJeans는 2022년 데뷔한 걸 그룹으로, 일상적인 감성과 1990~2000년대 팝·R&B의 질감을 현대적으로 풀어낸 음악과 자연스러운 퍼포먼스로 주목받았습니다.',
    '‘Attention’, ‘Hype Boy’, ‘Ditto’, ‘OMG’, ‘Super Shy’가 국내외 차트에서 사랑받았고, 짧은 러닝타임과 영상·그래픽을 유기적으로 연결한 앨범 경험으로 강한 인상을 남겼습니다.'
  ], '[{"year":"2022","text":"‘Attention’ 뮤직비디오를 먼저 공개한 뒤 미니 앨범 《New Jeans》로 데뷔.","source_url":"https://en.wikipedia.org/wiki/NewJeans"},{"year":"2022","text":"‘Ditto’와 ‘OMG’를 발표하며 국내 음원 차트 장기 흥행.","source_url":"https://en.wikipedia.org/wiki/NewJeans"},{"year":"2023","text":"미니 앨범 《Get Up》으로 Billboard 200 1위 달성.","source_url":"https://en.wikipedia.org/wiki/NewJeans"},{"year":"2023","text":"‘Super Shy’와 ‘ETA’가 글로벌 차트에 진입.","source_url":"https://en.wikipedia.org/wiki/Get_Up_(EP)"},{"year":"2024","text":"‘How Sweet’과 일본 데뷔 싱글 ‘Supernatural’을 발표.","source_url":"https://en.wikipedia.org/wiki/NewJeans"}]'::jsonb,
  '[{"year":"2022","text":"Melon Music Awards New Artist of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NewJeans"},{"year":"2023","text":"MAMA Awards Artist of the Year와 Song of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NewJeans"},{"year":"2023","text":"Billboard Music Awards Top Global K-Pop Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NewJeans"},{"year":"2024","text":"Golden Disc Awards 디지털 음원 대상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NewJeans"}]'::jsonb),

  ('enhypen-q99479445', array[
    'ENHYPEN은 오디션 프로그램 《I-LAND》를 통해 결성된 BELIFT LAB의 보이 그룹입니다. 성장의 경계와 연결, 욕망을 판타지 서사와 연결한 앨범 세계관과 강한 퍼포먼스를 선보입니다.',
    '《BORDER》 시리즈에서 출발해 《DIMENSION》, 《MANIFESTO》, 《DARK BLOOD》, 《ROMANCE : UNTOLD》로 이야기를 확장하며 한국·일본·글로벌 투어에서 팬덤 ENGENE과 만나고 있습니다.'
  ], '[{"year":"2020","text":"미니 앨범 《BORDER : DAY ONE》과 ‘Given-Taken’으로 데뷔.","source_url":"https://en.wikipedia.org/wiki/Enhypen"},{"year":"2021","text":"정규 1집 《DIMENSION : DILEMMA》가 밀리언셀러 기록.","source_url":"https://en.wikipedia.org/wiki/Enhypen"},{"year":"2022","text":"첫 월드 투어 MANIFESTO를 시작.","source_url":"https://en.wikipedia.org/wiki/Enhypen"},{"year":"2023","text":"《DARK BLOOD》와 ‘Bite Me’로 다크 판타지 서사를 확장.","source_url":"https://en.wikipedia.org/wiki/Dark_Blood_(EP)"},{"year":"2024","text":"정규 2집 《ROMANCE : UNTOLD》 발표.","source_url":"https://en.wikipedia.org/wiki/Enhypen_discography"}]'::jsonb,
  '[{"year":"2021","text":"Golden Disc Awards 신인상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Enhypen"},{"year":"2021","text":"Seoul Music Awards 신인상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Enhypen"},{"year":"2022","text":"MAMA Awards Worldwide Fans’ Choice 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Enhypen"},{"year":"2024","text":"Golden Disc Awards 음반 본상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Enhypen"}]'::jsonb),

  ('tomorrow-x-together-q60550265', array[
    '투모로우바이투게더는 수빈, 연준, 범규, 태현, 휴닝카이로 구성된 BIGHIT MUSIC의 5인조 그룹입니다. 소년의 성장과 우정, 불안과 희망을 장르 변화가 큰 음악과 섬세한 앨범 서사로 표현합니다.',
    '《꿈의 장》에서 시작해 《혼돈의 장》, 《이름의 장》, 《별의 장》으로 세계관을 확장했으며 록·팝·하이퍼팝을 넘나드는 음악과 정교한 무대로 글로벌 팬덤 MOA와 만나고 있습니다.'
  ], '[{"year":"2019","text":"미니 앨범 《꿈의 장: STAR》와 ‘어느날 머리에서 뿔이 자랐다’로 데뷔.","source_url":"https://ibighit.com/txt/kor/profile/"},{"year":"2020","text":"《minisode1 : Blue Hour》로 청량한 팝 색을 확장.","source_url":"https://ibighit.com/txt/kor/discography/"},{"year":"2021","text":"《혼돈의 장: FREEZE》와 ‘0X1=LOVESONG’ 발표.","source_url":"https://ibighit.com/txt/kor/discography/"},{"year":"2023","text":"《이름의 장: TEMPTATION》으로 Billboard 200 1위 달성.","source_url":"https://en.wikipedia.org/wiki/Tomorrow_X_Together"},{"year":"2025","text":"《The Star Chapter: TOGETHER》로 별의 장 서사를 이어감.","source_url":"https://ibighit.com/txt/kor/discography/"}]'::jsonb,
  '[{"year":"2019","text":"MAMA Awards Best New Male Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Tomorrow_X_Together"},{"year":"2019","text":"Melon Music Awards 신인상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Tomorrow_X_Together"},{"year":"2023","text":"MTV Video Music Awards PUSH Performance of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Tomorrow_X_Together"},{"year":"2024","text":"Golden Disc Awards 음반 본상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Tomorrow_X_Together"}]'::jsonb),

  ('ateez-q59793088', array[
    'ATEEZ는 홍중, 성화, 윤호, 여상, 산, 민기, 우영, 종호로 구성된 KQ Entertainment의 8인조 그룹입니다. 항해와 자유, 청춘의 저항을 연결한 세계관과 폭발적인 퍼포먼스로 강한 무대 서사를 만듭니다.',
    '《TREASURE》와 《ZERO : FEVER》 시리즈를 거쳐 《THE WORLD》, 《GOLDEN HOUR》로 음악의 규모를 키웠으며, 월드 투어와 페스티벌을 통해 글로벌 팬덤 ATINY와 만나고 있습니다.'
  ], '[{"year":"2018","text":"미니 앨범 《TREASURE EP.1: All to Zero》로 데뷔.","source_url":"https://en.wikipedia.org/wiki/Ateez"},{"year":"2020","text":"《ZERO : FEVER Part.1》으로 새 앨범 서사를 시작.","source_url":"https://en.wikipedia.org/wiki/Ateez_discography"},{"year":"2023","text":"‘BOUNCY’와 정규 2집 《THE WORLD EP.FIN : WILL》 발표.","source_url":"https://en.wikipedia.org/wiki/Ateez"},{"year":"2024","text":"Coachella 무대에 오른 최초의 K-pop 보이 그룹이 됨.","source_url":"https://en.wikipedia.org/wiki/Ateez"},{"year":"2025","text":"《GOLDEN HOUR : Part.3》와 글로벌 투어로 활동 확장.","source_url":"https://en.wikipedia.org/wiki/Ateez_discography"}]'::jsonb,
  '[{"year":"2019","text":"MAMA Awards Worldwide Fans’ Choice 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Ateez"},{"year":"2020","text":"The Fact Music Awards Global Hottest상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Ateez"},{"year":"2024","text":"iHeartRadio Music Awards K-pop Artist of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Ateez"},{"year":"2024","text":"MTV Europe Music Awards Best K-Pop 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Ateez"}]'::jsonb),

  ('exo-q494717', array[
    'EXO는 SM Entertainment의 보이 그룹으로, 강한 보컬 라인과 정교한 퍼포먼스, 초능력을 모티프로 한 세계관을 바탕으로 활동해 왔습니다. 유닛 EXO-CBX·EXO-SC와 멤버별 솔로 활동도 활발합니다.',
    '‘Growl’, ‘Call Me Baby’, ‘Monster’, ‘Love Shot’ 등 여러 세대의 대표곡을 남겼고, 연속 밀리언셀러 기록과 대형 투어를 통해 K-pop의 글로벌 확장기에 중요한 역할을 했습니다.'
  ], '[{"year":"2012","text":"미니 앨범 《MAMA》로 한국과 중국에서 데뷔.","source_url":"https://en.wikipedia.org/wiki/Exo"},{"year":"2013","text":"정규 1집 《XOXO》와 ‘Growl’로 첫 밀리언셀러 기록.","source_url":"https://en.wikipedia.org/wiki/Exo"},{"year":"2015","text":"《EXODUS》와 ‘Call Me Baby’로 활동 규모 확대.","source_url":"https://en.wikipedia.org/wiki/Exo_discography"},{"year":"2018","text":"정규 5집 《DON’T MESS UP MY TEMPO》와 ‘Love Shot’ 발표.","source_url":"https://en.wikipedia.org/wiki/Exo_discography"},{"year":"2023","text":"정규 7집 《EXIST》로 그룹 앨범 활동 재개.","source_url":"https://en.wikipedia.org/wiki/Exist_(Exo_album)"}]'::jsonb,
  '[{"year":"2013","text":"《XOXO》로 MAMA Awards Album of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Exo"},{"year":"2014","text":"MAMA Awards Artist of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Exo"},{"year":"2016","text":"MAMA Awards Album of the Year 4년 연속 수상 기록.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Exo"},{"year":"2017","text":"Guinness World Records가 MAMA 대상 최다 수상 기록을 등재.","source_url":"https://en.wikipedia.org/wiki/Exo"}]'::jsonb),

  ('red-velvet-q17466114', array[
    'Red Velvet은 아이린, 슬기, 웬디, 조이, 예리로 구성된 SM Entertainment의 걸 그룹입니다. 밝고 대담한 Red 콘셉트와 부드럽고 성숙한 Velvet 콘셉트를 오가며 폭넓은 음악을 선보입니다.',
    '‘Dumb Dumb’, ‘Russian Roulette’, ‘Red Flavor’, ‘Bad Boy’, ‘Psycho’, ‘Cosmic’ 등 독특한 팝 사운드와 탄탄한 보컬 하모니가 살아 있는 대표곡을 꾸준히 발표했습니다.'
  ], '[{"year":"2014","text":"디지털 싱글 ‘Happiness’로 데뷔.","source_url":"https://en.wikipedia.org/wiki/Red_Velvet_(group)"},{"year":"2015","text":"예리가 합류하고 첫 미니 앨범 《Ice Cream Cake》 발표.","source_url":"https://en.wikipedia.org/wiki/Red_Velvet_(group)"},{"year":"2017","text":"《The Red Summer》의 ‘Red Flavor’가 대표 여름곡으로 흥행.","source_url":"https://en.wikipedia.org/wiki/Red_Velvet_discography"},{"year":"2019","text":"《The ReVe Festival: Finale》와 ‘Psycho’ 발표.","source_url":"https://en.wikipedia.org/wiki/Red_Velvet_discography"},{"year":"2024","text":"데뷔 10주년에 미니 앨범 《Cosmic》 발표.","source_url":"https://en.wikipedia.org/wiki/Cosmic_(Red_Velvet_EP)"}]'::jsonb,
  '[{"year":"2015","text":"Golden Disc Awards 신인상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Red_Velvet"},{"year":"2017","text":"MAMA Awards Best Female Group 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Red_Velvet"},{"year":"2018","text":"Korean Music Awards Best Pop Song 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Red_Velvet"},{"year":"2019","text":"Asia Artist Awards Song of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Red_Velvet"}]'::jsonb),

  ('itzy-q60732823', array[
    'ITZY는 예지, 리아, 류진, 채령, 유나로 구성된 JYP Entertainment의 걸 그룹입니다. 스스로를 사랑하고 남의 기준에 흔들리지 말자는 메시지를 강한 춤과 에너지 넘치는 무대로 전합니다.',
    '‘DALLA DALLA’, ‘WANNABE’, ‘LOCO’, ‘SNEAKERS’, ‘UNTOUCHABLE’ 등 개성 강한 곡을 발표했고 한국·일본 앨범과 월드 투어를 통해 팬덤 MIDZY와 만나고 있습니다.'
  ], '[{"year":"2019","text":"싱글 앨범 《IT’z Different》와 ‘DALLA DALLA’로 데뷔.","source_url":"https://en.wikipedia.org/wiki/Itzy"},{"year":"2020","text":"‘WANNABE’와 포인트 안무로 글로벌 인지도를 확대.","source_url":"https://en.wikipedia.org/wiki/Itzy"},{"year":"2021","text":"첫 정규 앨범 《CRAZY IN LOVE》 발표.","source_url":"https://en.wikipedia.org/wiki/Itzy_discography"},{"year":"2022","text":"《CHECKMATE》와 첫 월드 투어를 전개.","source_url":"https://en.wikipedia.org/wiki/Itzy"},{"year":"2024","text":"《BORN TO BE》와 두 번째 월드 투어로 활동 확장.","source_url":"https://en.wikipedia.org/wiki/Born_to_Be_(Itzy_album)"}]'::jsonb,
  '[{"year":"2019","text":"MAMA Awards Best New Female Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Itzy"},{"year":"2019","text":"Melon Music Awards 신인상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Itzy"},{"year":"2020","text":"Golden Disc Awards 디지털 음원 본상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Itzy"},{"year":"2022","text":"MAMA Awards Worldwide Fans’ Choice 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Itzy"}]'::jsonb),

  ('nmixx-q109307762', array[
    'NMIXX는 릴리, 해원, 설윤, 배이, 지우, 규진으로 구성된 JYP Entertainment SQU4D 소속 6인조 걸 그룹입니다. 서로 다른 장르를 한 곡 안에서 전환하는 MIXX POP과 탄탄한 라이브 역량을 팀의 정체성으로 삼습니다.',
    '《AD MARE》로 데뷔한 뒤 《expérgo》, 《Fe3O4》 시리즈, 《Blue Valentine》으로 음악적 서사를 넓혔으며 보컬·랩·퍼포먼스가 균형 잡힌 무대를 선보이고 있습니다.'
  ], '[{"year":"2022","text":"싱글 《AD MARE》와 ‘O.O’로 데뷔.","source_url":"https://nmixx.jype.com/discography"},{"year":"2023","text":"첫 미니 앨범 《expérgo》와 ‘Love Me Like This’ 발표.","source_url":"https://nmixx.jype.com/discography"},{"year":"2024","text":"《Fe3O4: BREAK》와 《Fe3O4: STICK OUT》으로 시리즈 전개.","source_url":"https://nmixx.jype.com/discography"},{"year":"2025","text":"《Fe3O4: FORWARD》와 정규 앨범 《Blue Valentine》 발표.","source_url":"https://nmixx.jype.com/discography"},{"year":"2026","text":"미니 앨범 《Heavy Serenade》로 활동을 이어감.","source_url":"https://nmixx.jype.com/discography"}]'::jsonb,
  '[{"year":"2022","text":"Asia Artist Awards Emotive상·New Wave상 수상.","source_url":"https://www.asiaartistawards.com/winner/w_2022.html"},{"year":"2023","text":"Asia Artist Awards Icon상·Best Choice상 수상.","source_url":"https://www.asiaartistawards.com/winner/2023"},{"year":"2024","text":"Korea Grand Music Awards IS Rising Star상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Nmixx"}]'::jsonb),

  ('babymonster-q115967938', array[
    'BABYMONSTER는 루카, 파리타, 아사, 아현, 라미, 로라, 치키타로 구성된 YG Entertainment의 걸 그룹입니다. 강한 힙합 기반 퍼포먼스와 보컬·랩 역량, 다국적 멤버의 개성을 함께 보여 줍니다.',
    '프리 데뷔 과정과 ‘BATTER UP’을 거쳐 7인 완전체 앨범 《BABYMONS7ER》로 공식 활동을 시작했고, 정규 앨범 《DRIP》과 후속 프로젝트로 글로벌 활동을 확대하고 있습니다.'
  ], '[{"year":"2023","text":"‘BATTER UP’을 공개하며 프리 데뷔 활동 시작.","source_url":"https://ygfamily.com/en/artists/babymonster/profile"},{"year":"2024","text":"7인 완전체 미니 앨범 《BABYMONS7ER》와 ‘SHEESH’로 공식 데뷔.","source_url":"https://ygfamily.com/en/artists/babymonster/discography"},{"year":"2024","text":"첫 정규 앨범 《DRIP》 발표.","source_url":"https://ygfamily.com/en/artists/babymonster/discography"},{"year":"2025","text":"미니 앨범 《WE GO UP》으로 활동 확장.","source_url":"https://ygfamily.com/en/artists/babymonster/discography"},{"year":"2026","text":"프로젝트 《춤 (CHOOM)》을 발표하며 퍼포먼스 색을 이어감.","source_url":"https://ygfamily.com/en/artists/babymonster/discography"}]'::jsonb,
  '[{"year":"2024","text":"MAMA Awards Fans’ Choice Female 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Babymonster"},{"year":"2024","text":"The Fact Music Awards Next Leader상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Babymonster"},{"year":"2025","text":"Golden Disc Awards Rookie Artist of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Babymonster"}]'::jsonb),

  ('zerobaseone-q117808633', array[
    'ZEROBASEONE은 Mnet 《BOYS PLANET》을 통해 결성된 보이 그룹입니다. 청춘의 시작과 성장, 팬덤 ZEROSE와 함께 완성하는 여정을 밝고 섬세한 음악과 퍼포먼스로 표현합니다.',
    '데뷔 앨범 《YOUTH IN THE SHADE》부터 《MELTING POINT》, 《You had me at HELLO》, 《BLUE PARADISE》까지 연속적인 앨범 서사를 전개하며 한국과 일본에서 활발히 활동했습니다.'
  ], '[{"year":"2023","text":"《BOYS PLANET》 최종회를 통해 멤버를 확정.","source_url":"https://en.wikipedia.org/wiki/ZeroBaseOne"},{"year":"2023","text":"미니 앨범 《YOUTH IN THE SHADE》와 ‘In Bloom’으로 데뷔.","source_url":"https://en.wikipedia.org/wiki/Youth_in_the_Shade"},{"year":"2023","text":"두 번째 미니 앨범 《MELTING POINT》 발표.","source_url":"https://en.wikipedia.org/wiki/ZeroBaseOne"},{"year":"2024","text":"《You had me at HELLO》와 일본 싱글로 활동 범위 확대.","source_url":"https://en.wikipedia.org/wiki/ZeroBaseOne_discography"},{"year":"2025","text":"《BLUE PARADISE》로 앨범 활동을 이어감.","source_url":"https://en.wikipedia.org/wiki/ZeroBaseOne_discography"}]'::jsonb,
  '[{"year":"2023","text":"MAMA Awards Best New Male Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_ZeroBaseOne"},{"year":"2023","text":"Melon Music Awards New Artist of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_ZeroBaseOne"},{"year":"2024","text":"Golden Disc Awards Rookie Artist of the Year 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_ZeroBaseOne"},{"year":"2024","text":"MAMA Awards Worldwide Fans’ Choice 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_ZeroBaseOne"}]'::jsonb),

  ('nct-127-q55624444', array[
    'NCT 127은 서울의 경도 127을 팀명에 담은 NCT의 고정 유닛입니다. 네오한 전자음과 힙합, 실험적인 곡 구조, 강도 높은 퍼포먼스를 중심으로 서울에서 세계로 뻗어가는 팀의 정체성을 표현합니다.',
    '‘Cherry Bomb’, ‘Kick It’, ‘Sticker’, ‘2 Baddies’, ‘Fact Check’, ‘Walk’ 등 개성 강한 대표곡을 쌓았으며 한국·일본·북미 투어와 멤버별 활동을 병행하고 있습니다.'
  ], '[{"year":"2016","text":"미니 앨범 《NCT #127》과 ‘Fire Truck’으로 데뷔.","source_url":"https://en.wikipedia.org/wiki/NCT_127"},{"year":"2017","text":"《LIMITLESS》와 《CHERRY BOMB》으로 음악 색을 확립.","source_url":"https://en.wikipedia.org/wiki/NCT_127_discography"},{"year":"2020","text":"정규 2집 《Neo Zone》과 ‘Kick It’으로 글로벌 성과 확대.","source_url":"https://en.wikipedia.org/wiki/Neo_Zone"},{"year":"2021","text":"정규 3집 《Sticker》가 트리플 밀리언셀러 기록.","source_url":"https://en.wikipedia.org/wiki/Sticker_(album)"},{"year":"2024","text":"정규 6집 《WALK》와 ‘삐그덕’을 발표.","source_url":"https://en.wikipedia.org/wiki/NCT_127_discography"}]'::jsonb,
  '[{"year":"2017","text":"MAMA Awards New Asian Artist 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NCT_127"},{"year":"2021","text":"MAMA Awards Worldwide Fans’ Choice 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NCT_127"},{"year":"2022","text":"Seoul Music Awards 대상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NCT_127"},{"year":"2023","text":"Circle Chart Music Awards 월드 한류 스타상 수상.","source_url":"https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_NCT_127"}]'::jsonb)
)
update public.artists artist
set bio_paragraphs = enriched.bio_paragraphs || coalesce(artist.bio_paragraphs, '{}'::text[]),
    history_items = enriched.history_items || coalesce(artist.history_items, '[]'::jsonb),
    award_items = enriched.award_items || coalesce(artist.award_items, '[]'::jsonb),
    updated_at = now()
from enriched
where artist.slug = enriched.slug;

do $$
declare
  enriched_count integer;
begin
  select count(*) into enriched_count
  from public.artists
  where active = true
    and cardinality(bio_paragraphs) >= 2
    and jsonb_array_length(history_items) >= 4
    and jsonb_array_length(award_items) >= 3;

  if enriched_count <> 20 then
    raise exception 'Expected 20 enriched artists, found %', enriched_count;
  end if;
end
$$;
